// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123104249_SeedSampleClasses")]
    partial class SeedSampleClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Domain.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Attended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DanceClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvitedByStudentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DanceClassId");

                    b.HasIndex("InvitedByStudentId");

                    b.HasIndex("PackageId");

                    b.HasIndex("StudentId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Domain.Models.DanceClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DanceStyleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DanceStyleId");

                    b.HasIndex("StudioId");

                    b.ToTable("DanceClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanceStyleId = 1,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            InstructorName = "Maria Santos",
                            Level = 0,
                            MaxStudents = 20,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 2,
                            DanceStyleId = 5,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            InstructorName = "Carlos Rivera",
                            Level = 1,
                            MaxStudents = 15,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 2
                        },
                        new
                        {
                            Id = 3,
                            DanceStyleId = 9,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            InstructorName = "Emma Wilson",
                            Level = 0,
                            MaxStudents = 10,
                            StartTime = new TimeSpan(0, 19, 0, 0, 0),
                            StudioId = 3
                        },
                        new
                        {
                            Id = 4,
                            DanceStyleId = 4,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            InstructorName = "Jake Thompson",
                            Level = 2,
                            MaxStudents = 18,
                            StartTime = new TimeSpan(0, 20, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 5,
                            DanceStyleId = 2,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            InstructorName = "Sofia Chen",
                            Level = 1,
                            MaxStudents = 20,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 6,
                            DanceStyleId = 6,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            InstructorName = "Carlos Rivera",
                            Level = 0,
                            MaxStudents = 15,
                            StartTime = new TimeSpan(0, 19, 0, 0, 0),
                            StudioId = 2
                        },
                        new
                        {
                            Id = 7,
                            DanceStyleId = 10,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 19, 30, 0, 0),
                            InstructorName = "Luna Park",
                            Level = 1,
                            MaxStudents = 8,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 4
                        },
                        new
                        {
                            Id = 8,
                            DanceStyleId = 3,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            InstructorName = "Nina Johnson",
                            Level = 0,
                            MaxStudents = 22,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 9,
                            DanceStyleId = 7,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            InstructorName = "Marco Rossi",
                            Level = 2,
                            MaxStudents = 14,
                            StartTime = new TimeSpan(0, 19, 0, 0, 0),
                            StudioId = 2
                        },
                        new
                        {
                            Id = 10,
                            DanceStyleId = 12,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            InstructorName = "Min-Jun Kim",
                            Level = 1,
                            MaxStudents = 20,
                            StartTime = new TimeSpan(0, 20, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 11,
                            DanceStyleId = 1,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            InstructorName = "Maria Santos",
                            Level = 1,
                            MaxStudents = 18,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 12,
                            DanceStyleId = 8,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            InstructorName = "Victoria Adams",
                            Level = 0,
                            MaxStudents = 16,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 2
                        },
                        new
                        {
                            Id = 13,
                            DanceStyleId = 9,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            InstructorName = "Emma Wilson",
                            Level = 1,
                            MaxStudents = 10,
                            StartTime = new TimeSpan(0, 19, 0, 0, 0),
                            StudioId = 3
                        },
                        new
                        {
                            Id = 14,
                            DanceStyleId = 5,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            InstructorName = "Carlos Rivera",
                            Level = 2,
                            MaxStudents = 16,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 15,
                            DanceStyleId = 11,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            InstructorName = "DJ Marcus",
                            Level = 0,
                            MaxStudents = 20,
                            StartTime = new TimeSpan(0, 19, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 16,
                            DanceStyleId = 4,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            InstructorName = "Jake Thompson",
                            Level = 3,
                            MaxStudents = 12,
                            StartTime = new TimeSpan(0, 20, 0, 0, 0),
                            StudioId = 2
                        },
                        new
                        {
                            Id = 17,
                            DanceStyleId = 6,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            InstructorName = "Carlos Rivera",
                            Level = 1,
                            MaxStudents = 20,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 18,
                            DanceStyleId = 10,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 19, 30, 0, 0),
                            InstructorName = "Luna Park",
                            Level = 2,
                            MaxStudents = 8,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            StudioId = 4
                        },
                        new
                        {
                            Id = 19,
                            DanceStyleId = 2,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            InstructorName = "Sofia Chen",
                            Level = 3,
                            MaxStudents = 15,
                            StartTime = new TimeSpan(0, 19, 30, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 20,
                            DanceStyleId = 1,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            InstructorName = "Maria Santos",
                            Level = 0,
                            MaxStudents = 25,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 21,
                            DanceStyleId = 3,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            InstructorName = "Nina Johnson",
                            Level = 1,
                            MaxStudents = 18,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            StudioId = 2
                        },
                        new
                        {
                            Id = 22,
                            DanceStyleId = 12,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            InstructorName = "Min-Jun Kim",
                            Level = 0,
                            MaxStudents = 22,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0),
                            StudioId = 1
                        },
                        new
                        {
                            Id = 23,
                            DanceStyleId = 9,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 13, 30, 0, 0),
                            InstructorName = "Emma Wilson",
                            Level = 2,
                            MaxStudents = 8,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0),
                            StudioId = 3
                        });
                });

            modelBuilder.Entity("Domain.Models.DanceStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DanceStyles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ballet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Contemporary"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hip-hop"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Salsa"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bachata"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tango"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ballroom"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pole Fitness"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aerial Silks"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Breakdancing"
                        },
                        new
                        {
                            Id = 12,
                            Name = "K-pop"
                        });
                });

            modelBuilder.Entity("Domain.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DanceStyleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RemainingClasses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DanceStyleId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Domain.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Domain.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAerialRigging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPoles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeSquareMeters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasAerialRigging = false,
                            HasPoles = false,
                            MaxCapacity = 25,
                            Name = "Studio A",
                            SizeSquareMeters = 120
                        },
                        new
                        {
                            Id = 2,
                            HasAerialRigging = false,
                            HasPoles = false,
                            MaxCapacity = 18,
                            Name = "Studio B",
                            SizeSquareMeters = 80
                        },
                        new
                        {
                            Id = 3,
                            HasAerialRigging = false,
                            HasPoles = true,
                            MaxCapacity = 12,
                            Name = "Studio C",
                            SizeSquareMeters = 60
                        },
                        new
                        {
                            Id = 4,
                            HasAerialRigging = true,
                            HasPoles = false,
                            MaxCapacity = 10,
                            Name = "Studio D",
                            SizeSquareMeters = 100
                        });
                });

            modelBuilder.Entity("Domain.Models.TrialUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DanceStyleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TrialDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DanceStyleId");

                    b.HasIndex("StudentId", "DanceStyleId")
                        .IsUnique();

                    b.ToTable("TrialUsages");
                });

            modelBuilder.Entity("Domain.Models.Booking", b =>
                {
                    b.HasOne("Domain.Models.DanceClass", "DanceClass")
                        .WithMany("Bookings")
                        .HasForeignKey("DanceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Student", "InvitedByStudent")
                        .WithMany("InvitedBookings")
                        .HasForeignKey("InvitedByStudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Package", "Package")
                        .WithMany("Bookings")
                        .HasForeignKey("PackageId");

                    b.HasOne("Domain.Models.Student", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanceClass");

                    b.Navigation("InvitedByStudent");

                    b.Navigation("Package");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Models.DanceClass", b =>
                {
                    b.HasOne("Domain.Models.DanceStyle", "DanceStyle")
                        .WithMany("DanceClasses")
                        .HasForeignKey("DanceStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Studio", "Studio")
                        .WithMany("DanceClasses")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanceStyle");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Domain.Models.Package", b =>
                {
                    b.HasOne("Domain.Models.DanceStyle", "DanceStyle")
                        .WithMany("Packages")
                        .HasForeignKey("DanceStyleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Student", "Student")
                        .WithMany("Packages")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanceStyle");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Models.TrialUsage", b =>
                {
                    b.HasOne("Domain.Models.DanceStyle", "DanceStyle")
                        .WithMany("TrialUsages")
                        .HasForeignKey("DanceStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Student", "Student")
                        .WithMany("TrialUsages")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanceStyle");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Models.DanceClass", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Domain.Models.DanceStyle", b =>
                {
                    b.Navigation("DanceClasses");

                    b.Navigation("Packages");

                    b.Navigation("TrialUsages");
                });

            modelBuilder.Entity("Domain.Models.Package", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Domain.Models.Student", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("InvitedBookings");

                    b.Navigation("Packages");

                    b.Navigation("TrialUsages");
                });

            modelBuilder.Entity("Domain.Models.Studio", b =>
                {
                    b.Navigation("DanceClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
